name: CI Pipeline

on: push

jobs:
  build-and-test:
    uses: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Setup Python
       uses: actions/python-setup@v5

     - name: Install dependecies
       run: pip install -r requirements.py

      
     - name: Run pytest
       run: pytest

